# This is a basic workflow to help you get started with Actions

name: Build JSON

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/checkout@v3
        with:
          repository: Aeroblast/book_sales_info
          path: book_sales_info
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1

      - name: generate json
        run: node book_sales_info/utils/build_data.js ./
        
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          commit_message: Auto Generate
          commit_user_name: Bot Aeroblast
          commit_user_email: 15964528+Aeroblast@users.noreply.github.com
          commit_author: Bot <15964528+Aeroblast@users.noreply.github.com>
          file_pattern: latest.json history.json
